export const team_members = [
  {
    name: "Abass Abdul-Azeez",
    position: "Convener",
    image: "/team/Abass.png",
    instagram:
      "https://www.instagram.com/abass_biola?igsh=MTJtZmdsenM4am96bA==",
    x: "https://x.com/AbassAbiolaA?t=jRc9U6Um-CawH6mwq7MV9g&s=09",
    linkedin:
      "https://www.linkedin.com/in/biola-abass?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    name: "Sheriffdeen Oladimeji",
    position: "Communications Team",
    image: "/team/Sherif.png",
    instagram: "",
    x: "",
    linkedin: "",
  },
  {
    name: "Yusuf Adua",
    position: "Sponsorship & Budgeting Team",
    image: "/team/adua.png",
    instagram: "",
    x: "",
    linkedin: "",
  },
  {
    name: "Afolabi Maryam",
    position: "UI/UX Designer & Community Manager",
    image: "/team/Maryam.png",
    instagram: "",
    x: "https://x.com/Oladoyin0?t=z8d3E2-WoFh5PU-OFdzSoQ&s=09",
    linkedin: "",
    other: "https://www.behance.net/afolabimaryam",
  },
  {
    name: "Ridwan Abdulkareem",
    position: "Curation Team & Web Developer",
    image: "/team/Ridwan.png",
    instagram: "https://www.instagram.com/elegant_ak?igsh=dHN3M2RpOTQwbzhy",
    x: "https://twitter.com/RidwanGboyegaAK",
    linkedin: "https://www.linkedin.com/in/ridwan-abdulkareem",
    other: "https://reedwane.com",
  },
  {
    name: "Abulaleem Lateef",
    position: "Event Manager",
    image: "/team/lateef.png",
    instagram: "",
    x: "",
    linkedin: "",
  },
  {
    name: "Oyero Abiodun",
    position: "Sponsorship",
    image: "/team/Oyero.png",
    instagram: "https://www.instagram.com/excellent_629",
    x: "https://www.x.com/excellent_629",
    linkedin: "https://www.linkedin.com/in/oyeroabiodun",
  },
  {
    name: "Hasanah Bolaji",
    position: "Communications Team",
    image: "/team/Bolaji.png",
    instagram: "",
    x: "",
    linkedin: "",
  },
  {
    name: "Summayyah Adenle",
    position: "Curation Team",
    image: "/team/Adenle.png",
    instagram: "",
    x: "",
    linkedin: "",
  },
  {
    name: "Oluwaseun Ojo",
    position: "Event Manager",
    image: "/team/Ojo.png",
    instagram: "",
    x: "",
    linkedin: "",
  },
  {
    name: "Mojeed Ajibola",
    position: "Event Manager",
    image: "/team/ajibola.png",
    instagram: "",
    x: "",
    linkedin: "",
  },
  {
    name: "Rasheed Mudashir",
    position: "Web Developer",
    image: "/team/Rasheed.png",
    instagram: "",
    x: "",
    linkedin: "",
  },
  {
    name: "Jaiye Abdul",
    position: "Brand Designer",
    image: "/team/jaiye.png",
    instagram: "www.instagram.com/jaiye_abdul",
    x: "x.com/jaiye_abdul",
    linkedin:
      "https://www.linkedin.com/in/abdulraqib-durojaiye-aa52b117b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    name: "Kawthar Abdulmojeed",
    position: "Communications Team",
    image: "/team/kawthar.png",
    instagram: "",
    x: "",
    linkedin: "",
  },
];

export const speakers = [
  {
    name: "Dr. Sanusi Lafiagi",
    position: "Writer, Teacher, Counselor, and Brand Influencer",
    image: "/speakers/Sanusi.png",
  },
  {
    name: "Chief Saheed Oladele",
    position: "Chairman at Erudite Group, and The Baameko of Ibadan Land",
    image: "/speakers/Saheed.png",
  },
  {
    name: "Sanni Hassan",
    position: "Bespoke Tailor and Professional Event Host",
    image: "/speakers/Sanni.png",
  },
  {
    name: "Dr. Mrs Kola Aderoju",
    position: "Lecturer, Kola Daisi University",
    image: "/speakers/aderoju.png",
  },
];
